name: Build and Deploy Run Biscuit Run to Itch.io

on:
  push:
    branches:
      - main
  workflow_dispatch: # Allows manual triggering

env:
  GODOT_VERSION: 4.3-stable
  EXPORT_NAME: run-biscuit-run
  PROJECT_PATH: .
  ITCH_USER: mercutio32
  ITCH_GAME: run-biscuit-run

jobs:
  export-web:
    name: Build and Deploy Web Game
    runs-on: ubuntu-20.04
    container:
      image: barichello/godot-ci:4.3
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          lfs: true
      
      - name: Setup Godot Templates
        run: |
          mkdir -v -p ~/.local/share/godot/export_templates/
          mv /root/.local/share/godot/export_templates/${GODOT_VERSION} ~/.local/share/godot/export_templates/${GODOT_VERSION}
      
      - name: Web Build
        run: |
          mkdir -v -p build/web
          godot --headless --verbose --export-release "Web" build/web/index.html
      
      - name: Install Butler
        run: |
          curl -L -o butler.zip https://broth.itch.ovh/butler/linux-amd64/LATEST/archive/default
          unzip butler.zip
          chmod +x butler
          ./butler -V
      
      - name: Deploy to Itch.io
        env:
          BUTLER_API_KEY: ${{ secrets.BUTLER_CREDENTIALS }}
        run: |
          ./butler push build/web $ITCH_USER/$ITCH_GAME:web